### ISSUE TITLE
AFK causes conditions icons to duplicate

### ISSUE THREAD

**Issue by kaizenmc** [Mr-Byte/fast-flip#11]
When using AFK in PF2e the condition icons duplicate.  As far as I can tell this is just cosmetic and refreshing the screen removes them. 
 
![image](https://user-images.githubusercontent.com/63857994/210647052-ba10da2f-7d6d-42fd-96a0-1acd682c0edc.png)

**Comment by kaizenmc** [comment]
Also, if you add / remove too many times in a row (4 or 5) it locks the orange AFK image on the token and now it won't come off.

**Comment by Mr-Byte** [comment]
Hi there! Sorry I haven't had a chance to respond to this.  I'm going to try and take a look at this over the weekend and see what I can do to fix it.  The way I'm currently handling the AFK marker is a bit of a hack anyway and there's definitely better, more robust ways to handle this.

**Comment by kaizenmc** [comment]
Thank you for the response.  That would be great if you can get it working, your AFK overlay makes noting AFK players super easy.  Love this add on!

**Comment by Mr-Byte** [comment]
I just released v3.2.0 that should hopefully fix this issue.  I'm hoping to do some additional improvements to the AFK overlay functionality since I had to rewrite it from scratch to support Foundry V10 properly, but I'll do those in a future update. Wanted to make sure this bug got fixed.

Please open issues for any additional problems you find!
